name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: parking_controller

      - uses: actions/checkout@v4
        with:
          repository: rss2025-4/libracecar
          ref: 9633b011b8a4e611fce93b3e637e45d317216e45
          path: libracecar
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v4
        with:
          repository: mit-rss/visual_servoing
          ref: 9b1e45adff9cb45f7cd5011c2a082028c160712e
          path: visual_servoing

      - uses: actions/checkout@v4
        with:
          repository: Sebastian-Garcia/racecar_simulator
          ref: 0e20c77dcc408c7b4babf153ef3baeadf5448ce8
          path: racecar_simulator

      - uses: docker/setup-buildx-action@v3

      - run: |
          cd parking_controller/tests
          export DOCKER_UID=$(id -u)
          export DOCKER_GID=$(id -g)
          docker compose run --build racecar
